sonar.projectKey=FranGenoud01_Repo-Genoud-Nicol-s-y-Aguado
sonar.organization=frangenoud01
sonar.python.coverage.reportPaths=coverage.xml
sonar.sources=.
sonar.exclusions=**/*test*.py
sonar.tests=.
sonar.test.inclusions=**/*test*.py 